### ISSUE TITLE
[propose]: Add -x and -y options

### ISSUE THREAD

**Issue by dninomiya** [juhanakristian/tailwind-gradient-mask-image#10]
Here is the translation of your text into English:

I propose adding the -x and -y options. This would be useful for fading out both ends, such as with a marquee. If there are no issues, I can also create a Pull Request!

```html
<div class="gradient-mask-x"></div>
<div class="gradient-mask-y"></div>
```

**Comment by juhanakristian** [comment]
Hi @dninomiya I've just pushed 1.2.0 which includes the possibility to set arbitrary steps. 
For example you can do the following to fade from left and right
`gradient-mask-l-[transparent,rgba(0,0,0,1)_50%,transparent_100%]`

Check this playgound for a complete example
https://play.tailwindcss.com/QN6oUs1x0q

**Comment by dninomiya** [comment]
@juhanakristian 
Thank you!🫡
