### ISSUE TITLE
No way to disable rule on breakpoints

### ISSUE THREAD

**Issue by Sengulair** [juhanakristian/tailwind-gradient-mask-image#4]
@juhanakristian
For [Targeting mobile screens](https://tailwindcss.com/docs/responsive-design#targeting-mobile-screens) we can use just a rule, but there is no way to disable gradient mask on other breakpoints

**Comment by TheMikeyRoss** [comment]
I think this package is abandoned by @juhanakristian

**Comment by juhanakristian** [comment]
The package is not abandoned but I have been busy with other things. 

I'm happy to welcome PRs for this issue. Otherwise I'm not sure when I'll be able to fix it.

**Comment by ColColty** [comment]
Hi @juhanakristian, my PR #7 handles this issue and also adds arbitrary values. Let me know if it looks good for you, or if I need to change something.

**Comment by juhanakristian** [comment]
This is now fixed in 1.2.0 thanks to @ColColty  🥳
